# -*- coding: utf-8 -*-
"""가계부분류

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-3U0o-EzhS0TEiEgNphni3jiegkdZ2JW
"""

# https://firework-ham.tistory.com/56
pip install beautifulsoup4

from urllib.request import urlopen
from bs4 import BeautifulSoup

# 문자 영수증 인식
text_bill = '[Web발신][신한체크승인] 김*지(6423) 04/28 14:47 (금액)6,500원 주식회사 랑데자뷰대학로'
#text_bill = '[Web발신][신한체크승인] 김*지(6423) 04/01 14:30 (금액)5,300원 투썸플레이스'
date = text_bill.split(' ')[2]
store_name = text_bill.split(' ')[6]
amount = (text_bill.split(' ')[4])[4:-1]

## 문자 영수증 결제처 이름의 형태의 변화 오류!!!!
# 문자 영수증 결체저 이름 내에서 띄어쓰기

# 검색 키워드 퍼센트 인코딩 처리 : https://hogni.tistory.com/65
import requests
import urllib

store_name = urllib.parse.quote(store_name)
url = f'https://search.naver.com/search.naver?where=nexearch&sm=top_hty&fbm=1&ie=utf8&query={store_name}'

r = requests.get(url)
soup = BeautifulSoup(r.text, 'html.parser')
category_tag = soup.find_all("span", {"class":["category", "_1tj6W", "_3lc1U"]})
category_tag
keyword = category_tag[0].text
keyword

# 웹 크롤링 : https://webnautes.tistory.com/779
html = urlopen("https://search.naver.com/search.naver?where=nexearch&sm=top_hty&fbm=1&ie=utf8&query=%EB%9E%91%EB%8D%B0%EC%9E%90%EB%B7%B0+%EB%8C%80%ED%95%99%EB%A1%9C")
bsObject = BeautifulSoup(html, "html.parser")

#bsObject.find_all("span")

bsObject.find_all("span", {"class":["category", "_1tj6W", "_3lc1U"]}) # category, _1tj6W, _3lc1U

category_tag = bsObject.find("span", {"class":["category", "_1tj6W", "_3lc1U"]})
category_tag
keyword = category_tag.text
keyword

import pandas as pd
from pandas import Series, DataFrame

df = pd.read_excel('drive/MyDrive/Colab Notebooks/가계부분류.xlsx')
df = pd.DataFrame(df)

category = ''
column_name = ['음식점', '교통', "식료품", "쇼핑", "카페", "뷰티", "병원/약국", "애완동물", "교육/육아", "레저/스포츠", "여행/숙박"]

for i in range(11):
  for j in range(len(df.음식점)):
    if keyword == df[column_name[i]][j]:
      category = column_name[i]
      print(keyword, " : ", category)
      break

# 파일에 데이터 저장되도록 : https://myjamong.tistory.com/51
from openpyxl import Workbook
from openpyxl.styles import PatternFill, Color

user_name = 'user1'

write_wb = Workbook()
# 이름이 있는 시트를 생성
write_ws = write_wb.create_sheet(user_name)

# 'user1' 시트에 작성
write_ws = write_wb.active

# 셀 단위로 추가
#for i in range(11):
#  write_ws.cell(1, i+1, column_name[i])
write_ws.cell(1, 1, '날짜')
write_ws.cell(1, 2, '사용내역')
write_ws.cell(1, 3, '지출분류')
write_ws.cell(1, 4, '지출')
#for i in range(1, 5):
#  write_ws.cell(row=1, column=i).fill = PatternFill(start_color='808080', end=color='808080', fill_type='solid')

# user1의 지출내역 추가
write_ws.cell(2, 1, date)
write_ws.cell(2, 2, keyword)
write_ws.cell(2, 3, category)
write_ws.cell(2, 4, amount)

write_wb.save('drive/MyDrive/Colab Notebooks/user1.xlsx')

